### ISSUE TITLE
Could you add at least English localization please?!

### ISSUE THREAD

**Issue by fabiocaccamo** [shaojiankui/ProfilesManager#1]

**Comment by shaojiankui** [comment]
English localization added!
https://github.com/shaojiankui/ProfilesManager/commit/eb29dfb398ef01d8f93c58ffb1386b94f70037ef

**Comment by fabiocaccamo** [comment]
@shaojiankui I just installed 1.0.0 release but I still see some un-localized texts.

![schermata 2017-02-08 alle 10 10 33](https://cloud.githubusercontent.com/assets/1035294/22730489/7b3ad9f8-ede7-11e6-8fbd-9d695d5f9624.png)

thanks for the quick support!

**Comment by shaojiankui** [comment]
what,do you use the english version mac os?

**Comment by fabiocaccamo** [comment]
No, my default language is Italian.

**Comment by shaojiankui** [comment]
here a test version for you,try try
http://dev.skyfox.org/ProfilesManager%202017-02-08%2018-00-38.zip

**Comment by fabiocaccamo** [comment]
perfect!
thanks
