### ISSUE TITLE
XCode 16 stores provisioning profiles in new location

### ISSUE THREAD

**Issue by ipad4** [shaojiankui/ProfilesManager#13]
Provisioning profiles are no longer located in ~/Library/MobileDevice/Provisioning Profiles/. The directory is not necessarily wiped during Xcode update but it's no longer updated from the Xcode UI. The new location is ~/Library/Developer/Xcode/UserData/Provisioning Profiles.

solution:
`ln -s ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles ~/Library/MobileDevice/Provisioning\ Profiles`

**Comment by shaojiankui** [comment]
It seems that xcode will read both directories

**Comment by shaojiankui** [comment]
done 2.7
