### ISSUE TITLE
请增加排序功能，创建时间

### ISSUE THREAD

**Issue by csc-EricWu** [shaojiankui/ProfilesManager#3]
请增加排序功能，创建时间，方便我们删除不必要的profile 文件

**Comment by shaojiankui** [comment]
https://github.com/shaojiankui/ProfilesManager/releases/tag/2.0
看看最新版能不能满足你

**Comment by shaojiankui** [comment]
点击列头部可以排序

**Comment by csc-EricWu** [comment]
很棒～

**Comment by csc-EricWu** [comment]
通过过期时间排序确实很管用，但这里有一点可以优化，由于我们的mobileprovision 会经常增加设备id ,造成下载下来的mobileprovision过期时间是一样的，CreateDate 时间不一样，打包的时候XCode 有可能会自动选择前一个mobileprovision，所以希望加一个CreateDate字段来排序，这样可以一眼看到哪些是最新的mobileprovision，让我选择删除比较旧的mobileprovision

**Comment by csc-EricWu** [comment]
另外可以增加一个序号的字段，可以一眼看到有多少个mobileprovision 文件

**Comment by shaojiankui** [comment]
不太可能，在文件夹中相同uuid的mobileprovision不会共存的，除非是xcode未关闭的缓存
~/Library/MobileDevice/Provisioning Profiles/ 很神奇的目录，我想做文件改名都做不了。不能同uuid profile文件共存，而且如果增加了设备重新生成的profile文件过期时间不会一样的吧。。。肯定会变

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/48460951-42a28980-e80c-11e8-992b-412dfef441a3.png)

其实我是想添加一个CreateDate 的title 并可以排序，这样我好看那个是最新的并管理它们。

**Comment by shaojiankui** [comment]
好，满足你。。一会我加上然后发布，你的app下次启动应该会自动提示更新。

**Comment by csc-EricWu** [comment]
好的，3Q

**Comment by shaojiankui** [comment]
这把完全ok了。。。，你打开app一会就应该会有提示。如果没有可以在这下载https://github.com/shaojiankui/ProfilesManager/releases/tag/2.2

**Comment by csc-EricWu** [comment]
很棒，已经很好用了，给你点个👍
