### ISSUE TITLE
请问大佬是否知道如何根据一个ipa包查看它具体是使用的哪个证书签名的呢？

### ISSUE THREAD

**Issue by NineCity** [shaojiankui/ProfilesManager#4]
我把一个.ipa文件解压后查看里面的*.mobileprovision文件，可以查看到DeveloperCertificates里包含了两个证书，但我不知道我的app具体是使用哪一个证书签名的，我是使用自动管理签名的，大佬可有什么方法？十分感谢

**Comment by shaojiankui** [comment]
mobileprovision中肯定没用，因为mobileprovision是打包前就生成了

**Comment by NineCity** [comment]
是这样的，我有一个企业账号，之前用同一台电脑创建了两个发布证书，每次都是自动管理签名发布app的，但是我不知道具体使用了哪一个证书去签名的。
然后那台电脑坏了，我现在换了一台电脑，我之前那两个证书都不能用了，因为新电脑本地没有私钥。企业账号最多只能生成2个发布证书，下次我想要发版的时候，就要移除一个发布证书，可是一旦我把当时用来签名的那个发布证书移除了，那么所有已经安装在用户手机上的app就会无法打开，所以我想知道我之前发布的app到底使用哪个证书签名的，只要我移除没有用来签名的那个证书，应该对已经安装的用户就没有影响了吧，所以想请问大佬有没有什么办法？

**Comment by youmoxiyou** [comment]
> 是这样的，我有一个企业账号，之前用同一台电脑创建了两个发布证书，每次都是自动管理签名发布app的，但是我不知道具体使用了哪一个证书去签名的。
> 然后那台电脑坏了，我现在换了一台电脑，我之前那两个证书都不能用了，因为新电脑本地没有私钥。企业账号最多只能生成2个发布证书，下次我想要发版的时候，就要移除一个发布证书，可是一旦我把当时用来签名的那个发布证书移除了，那么所有已经安装在用户手机上的app就会无法打开，所以我想知道我之前发布的app到底使用哪个证书签名的，只要我移除没有用来签名的那个证书，应该对已经安装的用户就没有影响了吧，所以想请问大佬有没有什么办法？

看你两个证书过期时间，mobileprovision中的`Expiration Date`最晚会和使用的证书过期时间是一样的。

**Comment by csc-EricWu** [comment]
搞一个证书不就妥了

**Comment by shaojiankui** [comment]
现在支持查看ipa里。拖进去就能看。 可以看具体证书
