### ISSUE TITLE
能否添加一列显示Bundle id 呢？

### ISSUE THREAD

**Issue by csc-EricWu** [shaojiankui/ProfilesManager#5]
1.能否添加一列显示Bundle id 呢？
2.能否增加brew cask  下载支持？

**Comment by shaojiankui** [comment]
bundleid已加 brew cask我也不懂啊。。。

**Comment by csc-EricWu** [comment]
大神，过期时间，和创建时间拿掉了？

**Comment by shaojiankui** [comment]
what没有啊。你点左上角的重置 试试。

**Comment by csc-EricWu** [comment]
确实不见了，目前只有3列了。还有一个issue 能实现吗？

**Comment by csc-EricWu** [comment]
是个bug 我修复了。提交了Pull Request 麻烦看一下
