### ISSUE TITLE
名字都显示不全，bundleid 都看不到

### ISSUE THREAD

**Issue by YelCode** [shaojiankui/ProfilesManager#6]
名字都显示不全，bundleid 都看不到
![QQ20200121-111928](https://user-images.githubusercontent.com/13357868/72772802-f2a92900-3c3f-11ea-8f22-14c371b6bf22.png)

**Comment by csc-EricWu** [comment]
所以增加一列bundleid 就最好不过了。

**Comment by shaojiankui** [comment]
你这profile名字咋都这样的。。。。是xcode生成的？

**Comment by shaojiankui** [comment]
@csc-EricWu   显示很简单。问题是搁哪显示啊。。。再加一列，展开后那列底下全是空白的 看着很怪。

**Comment by csc-EricWu** [comment]
放Filename or key 这一列挺好哈，显示这个也没啥用

**Comment by YelCode** [comment]
对啊 现在都是xcode 自动管理 那个行列限制最长的宽度了 去掉也可以
