### ISSUE TITLE
大神，可否在右键菜单中增加一项，复制路径的功能

### ISSUE THREAD

**Issue by csc-EricWu** [shaojiankui/ProfilesManager#7]
![image](https://user-images.githubusercontent.com/13517061/72949884-94f21980-3dc4-11ea-8d8d-1bebcffc0a1d.png)

**Comment by shaojiankui** [comment]
可以的。现在有点忙，年后有时间把你的建议都完善下。或者你可以自行修改后提交pull request，哈哈
