### ISSUE TITLE
大神，快速查看貌似不管用，已经安装插件

### ISSUE THREAD

**Issue by csc-EricWu** [shaojiankui/ProfilesManager#8]
![image](https://user-images.githubusercontent.com/13517061/73036812-bcf68100-3e87-11ea-9b86-104ec60bcbff.png)

**Comment by shaojiankui** [comment]
在profile文件上按空格没反应？？？

**Comment by csc-EricWu** [comment]
在文件上管用，在你这个软件里不管用

**Comment by shaojiankui** [comment]
quicklook 就是在文件上用的啊。。。。------------------ Original ------------------
